name: side_menu_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: THSarabunNew
      fonts:
        - asset: assets/fonts/THSarabunNew Bold.ttf
        - asset: assets/fonts/THSarabunNew Italic.ttf
          style: italic
    - family: Takowasabi
      fonts:
        - asset: assets/fonts/Demo_RDTakowasabi-Regular.ttf
